apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: flux-ref
  namespace: flux-system
spec:
  interval: 1m
  ref:
    branch: main
  url: https://github.com/farkasmate/flux-ref.git
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: grafana
  namespace: flux-system
spec:
  interval: 1m
  retryInterval: 30s
  timeout: 10s
  sourceRef:
    kind: GitRepository
    name: flux-ref
  path: ./grafana
  prune: true
  wait: true
