apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: flux-ref
spec:
  interval: 1m
  ref:
    branch: main
  url: https://github.com/farkasmate/flux-ref.git
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: grafana
spec:
  interval: 1m
  retryInterval: 30s
  timeout: 10s
  sourceRef:
    kind: GitRepository
    name: flux-ref
  path: ./grafana
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: values
        optional: false
  prune: true
  wait: true
